# DEVELOPMENT compose
#
# Используются переменные из .env.development
#

name: "fancy-faces-development"
services:
  db:
    container_name: "${DATABASE_CONTAINER_NAME}"
    image: postgres:15.3
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ${POSTGRES_VOLUME_DATA}:/var/lib/postgresql/data
    restart: unless-stopped