name: "fancy-faces-app"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    volumes:
#      - {SQLITE_VOLUME_DATA}:/app/database
    restart: unless-stopped
#volumes:
#  sqlite_data
