version: '3.8'

services:
  fancy-faces:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ${POSTGRES_VOLUME_DATA}:/var/lib/postgresql/data
#    volumes:
#      - /Users/raudbrand/Desktop/fancy-faces-postgres-data:/var/lib/postgresql/data
#      - ./:/app
#      - /app/node_modules
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/nextjs
#      - POSTGRES_USER=postgres
    command: sh -c "su postgres -c 'pg_ctl -D /var/lib/postgresql/data -l logfile start' && npm run dev"

volumes:
  postgres-data:
